server:
  port: 5000
spring:
  cloud:
    config:
      name: configserver
      server:
        git:
          uri: https://github.com/nguyenhuuchau/spring-cloud-config-example
#          uri: https://github.com/spring-cloud-samples/config-repo
#          uri: https://github.com/o7planning/spring-cloud-config-git-repo-example
          default-label: master
      label: master
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: TRACE
