server:
  port: 5000
spring:
  cloud:
    config:
      name: configserver
      server:
        git:
          uri: https://github.com/nguyenhuuchau/spring-cloud-demo
          search-paths: config*
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: TRACE
