server:
  port: 9981
spring:
  application:
    name: zuul-gateway-service
eureka:
  instance:
    appname: ZUUL-GATEWAY-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}

zuul:
  ignored-services: "*"
  routes:
    test-service:
      path: /test/**
      service-id: test-service
    user-service:
      path: /user/**
      service-id: user-service

